version: '3.8'

services:
  mtrade-express-postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mtrade-e-p
    ports:
      - "5433:5432"
    volumes:
      - mtrade_express-postgres_data:/var/lib/postgresql/data

volumes:
  mtrade_express-postgres_data:
